### ISSUE TITLE
How to ouput slider in blade template ?

### ISSUE THREAD

**Issue by david-dacruz** [pratik007kumar/laravel-slider#2]
Hi I'm news at laravel nd your documentation is not explaining how to output the slider on a blade template ? Thanks ahead

**Comment by costin101** [comment]
I am experiencing the same issue. Can someone help please?

**Comment by costin101** [comment]
Can anyone please answer if this can be used inside a template?

**Comment by pratik007kumar** [comment]
sorry for let reply 
after publishing the vendor you will find slider blade files in resources/view/vendor/pratik/slider 
you can modify and use according you requirement

**Comment by costin101** [comment]
Thank you 👍
